import type { PalmIssue } from "@/lib/palmistry/analyze";
import type { MarkingKind, MountKey } from "@/lib/palmistry/mounts";

/** Every string the palm reader shows, in English and Hindi. */
export const PALM_COPY = {
  en: {
    issues: {
      "back-of-hand": "Turn your palm to face the camera",
      "too-small": "Move your hand a little closer",
      "too-dark": "Find brighter light",
      "too-bright": "Too much glare — tilt your palm away from the light",
      curled: "Open your hand fully — keep the fingers straight and the palm flat",
      tilted: "Hold your palm square to the camera, not at an angle",
      glare: "Glare on the palm — tilt it slightly away from the light",
      "uneven-light": "The light is uneven — face a window or lamp so the whole palm is lit",
      blurry: "Hold steady — the picture is blurry",
    } as Record<PalmIssue, string>,
    showHand: "Show your whole open hand — palm and fingers — to the camera",
    steadying: (n: number, of: number) => `Steadying… ${n}/${of}`,
    holdToCapture: "Lines found — hold still to capture",
    tapShutter: "Lines found — tap the shutter",
    holdStill: "Hold still, flat and in good light…",
    loadingModel: "Loading the hand model…",
    cameraDeclined: "Camera permission was declined. Allow the camera in your browser settings, or upload a photo instead.",
    cameraFailed: "Couldn't start the camera here. You can upload a photo of your palm instead.",
    noHand: "No hand found in the picture. Show your whole open palm, fingers together, against a plain background.",
    readFailed: "Couldn't read that picture.",
    openFailed: "Couldn't open that image. Try a JPEG or PNG photo.",
    shutter: "Take photo and read palm",
    flip: "Flip",
    close: "Close",
    auto: "Auto-capture",
    openCamera: "Open camera",
    upload: "Upload a photo",
    private: "Everything runs on your device — your palm photo is never uploaded.",
    reading: "Reading your palm…",
    alt: "Your palm with its lines traced",
    lines: "Lines",
    mounts: "Mounts",
    retake: "Retake",
    checks: { sharp: "Sharp", light: "Even light", flat: "Flat, open hand", close: "Close enough", steadied: "Steadied over live frames" },
    backOfHand: (other: string) => `This looks like the back of the hand, or the ${other} hand — switch hands above if so, or retake with your palm facing the camera.`,
    mayBeOff: "The reading below may be off — a retake will help.",
    title: "Hasta Samudrika reading",
    right: "Right hand",
    left: "Left hand",
    otherHand: { Right: "left", Left: "right" },
    mountsTitle: "The mounts (parvatas)",
    mountsBody: "Each mount belongs to a graha. Markings are read from the photo; how full a mount is can't be seen in a flat photo, so press each one gently and choose what you feel.",
    compare: "Compare with kundli",
    none: "None",
    strongest: (names: string, planet: string) => `Strongest mounts: ${names} — ${planet} sets the tone of your hand.`,
    notInView: "Not in view",
    pressed: "When pressed it feels",
    fullness: { flat: "Flat", normal: "Normal", full: "Full" },
    fingersTitle: "Fingers and their grahas",
    signs: { star: "Possible star", cross: "Possible cross", grille: "Grille of fine lines", vertical: "Vertical lines", clear: "Clear" } as Record<MarkingKind, string>,
    mountShort: {
      jupiter: "Jupiter",
      saturn: "Saturn",
      sun: "Sun",
      mercury: "Mercury",
      upperMars: "Upper Mars",
      lowerMars: "Lower Mars",
      venus: "Venus",
      moon: "Moon",
      rahu: "Rahu",
      ketu: "Ketu",
    } as Record<MountKey, string>,
    showHindiName: true,
  },
  hi: {
    issues: {
      "back-of-hand": "हथेली कैमरे की ओर करें",
      "too-small": "हाथ थोड़ा पास लाएँ",
      "too-dark": "ज़्यादा रोशनी में आएँ",
      "too-bright": "बहुत चमक है — हथेली को रोशनी से थोड़ा हटाएँ",
      curled: "हाथ पूरा खोलें — उँगलियाँ सीधी और हथेली सपाट रखें",
      tilted: "हथेली कैमरे के ठीक सामने रखें, तिरछी नहीं",
      glare: "हथेली पर चमक है — उसे रोशनी से थोड़ा हटाएँ",
      "uneven-light": "रोशनी असमान है — खिड़की या लैंप की ओर मुँह करें ताकि पूरी हथेली रोशन हो",
      blurry: "स्थिर रहें — तस्वीर धुंधली है",
    } as Record<PalmIssue, string>,
    showHand: "पूरा खुला हाथ — हथेली और उँगलियाँ — कैमरे को दिखाएँ",
    steadying: (n: number, of: number) => `स्थिर हो रहा है… ${n}/${of}`,
    holdToCapture: "रेखाएँ मिल गईं — फ़ोटो के लिए स्थिर रहें",
    tapShutter: "रेखाएँ मिल गईं — शटर दबाएँ",
    holdStill: "स्थिर, सपाट और अच्छी रोशनी में रखें…",
    loadingModel: "हाथ पहचानने का मॉडल लोड हो रहा है…",
    cameraDeclined: "कैमरा अनुमति नहीं मिली। ब्राउज़र सेटिंग में कैमरा चालू करें, या फ़ोटो अपलोड करें।",
    cameraFailed: "यहाँ कैमरा शुरू नहीं हो सका। आप हथेली की फ़ोटो अपलोड कर सकते हैं।",
    noHand: "तस्वीर में हाथ नहीं मिला। सादे पृष्ठभूमि पर पूरी खुली हथेली, उँगलियाँ साथ रखकर दिखाएँ।",
    readFailed: "वह तस्वीर पढ़ी नहीं जा सकी।",
    openFailed: "वह तस्वीर खुल नहीं सकी। JPEG या PNG फ़ोटो आज़माएँ।",
    shutter: "फ़ोटो लें और हथेली पढ़ें",
    flip: "पलटें",
    close: "बंद करें",
    auto: "स्वतः फ़ोटो",
    openCamera: "कैमरा खोलें",
    upload: "फ़ोटो अपलोड करें",
    private: "सब कुछ आपके डिवाइस पर चलता है — आपकी हथेली की फ़ोटो कभी अपलोड नहीं होती।",
    reading: "आपकी हथेली पढ़ी जा रही है…",
    alt: "रेखाओं के साथ आपकी हथेली",
    lines: "रेखाएँ",
    mounts: "पर्वत",
    retake: "फिर से लें",
    checks: { sharp: "स्पष्ट", light: "समान रोशनी", flat: "सपाट, खुला हाथ", close: "पर्याप्त पास", steadied: "कई फ़्रेम से स्थिर" },
    backOfHand: (other: string) => `यह हाथ का पिछला भाग या ${other} हाथ लगता है — ऐसा हो तो ऊपर हाथ बदलें, या हथेली कैमरे की ओर करके फिर से फ़ोटो लें।`,
    mayBeOff: "नीचे का फल सटीक न हो — फिर से फ़ोटो लेना मदद करेगा।",
    title: "हस्त सामुद्रिक फल",
    right: "दायाँ हाथ",
    left: "बायाँ हाथ",
    otherHand: { Right: "बायाँ", Left: "दायाँ" },
    mountsTitle: "पर्वत",
    mountsBody: "हर पर्वत एक ग्रह का है। चिह्न फ़ोटो से पढ़े जाते हैं; पर्वत कितना उभरा है यह सपाट फ़ोटो में नहीं दिखता, इसलिए हर पर्वत को हल्का दबाकर जैसा लगे वैसा चुनें।",
    compare: "कुंडली से मिलाएँ",
    none: "कोई नहीं",
    strongest: (names: string, planet: string) => `सबसे प्रबल पर्वत: ${names} — आपके हाथ का स्वर ${planet} तय करते हैं।`,
    notInView: "दिखाई नहीं दिया",
    pressed: "दबाने पर कैसा लगता है",
    fullness: { flat: "सपाट", normal: "सामान्य", full: "उभरा" },
    fingersTitle: "उँगलियाँ और उनके ग्रह",
    signs: { star: "संभावित तारा", cross: "संभावित क्रॉस", grille: "बारीक रेखाओं की जाली", vertical: "खड़ी रेखाएँ", clear: "स्पष्ट" } as Record<MarkingKind, string>,
    mountShort: {
      jupiter: "गुरु",
      saturn: "शनि",
      sun: "सूर्य",
      mercury: "बुध",
      upperMars: "उच्च मंगल",
      lowerMars: "निम्न मंगल",
      venus: "शुक्र",
      moon: "चंद्र",
      rahu: "राहु",
      ketu: "केतु",
    } as Record<MountKey, string>,
    showHindiName: false,
  },
};

export type PalmCopy = (typeof PALM_COPY)["en"];
