import type { VargaKey } from "./constants";

/**
 * Per-varga, per-house domain framing. D1 deliberately has no entry here —
 * its house-by-house reading is already universal/general-purpose (that *is*
 * its correct framing; see `HOUSE_SIGNIFICATION` in `content.ts`), so
 * `ChartDetail` never looks one up for the D1 chart. Every other divisional
 * chart gets its own set of 12 phrases so a chart's house analysis actually
 * speaks to what that chart is for (e.g. D10 house 10 reads as the peak of
 * career, not the generic "career, public standing" of D1's house 10).
 */
export type VargaLensKey = Exclude<VargaKey, "D1">;

export const VARGA_LENS: Record<VargaLensKey, { domain: string; houses: Record<number, string> }> = {
  D2: {
    domain: "wealth and the flow of financial resources",
    houses: {
      1: "your basic capacity to earn and hold money — the wealth-personality itself",
      2: "liquid savings, bank balance, and the family's core financial footing",
      3: "money earned through your own effort, courage, and short-term hustle",
      4: "real estate, fixed deposits, and the financial comfort of home",
      5: "money that flows from speculation, investments, and creative ventures",
      6: "debts owed, financial obstacles, and money lost to disputes or health",
      7: "wealth built jointly with a partner or through business partnerships",
      8: "sudden financial gains or losses, insurance, and inherited or shared money",
      9: "wealth earned through fortune, higher learning, or a father's resources",
      10: "income and financial standing generated through career and public work",
      11: "gains, profits, and the steady accumulation of wealth over time",
      12: "expenditure, financial loss, and money spent abroad or given away",
    },
  },
  D3: {
    domain: "siblings, courage, and short efforts and journeys",
    houses: {
      1: "your raw courage, initiative, and physical vitality",
      2: "the collective voice and shared resources of siblings and close kin",
      3: "the core strength of the bond with your siblings",
      4: "the emotional comfort or friction siblings bring into the home",
      5: "the creative and intellectual spark shared with siblings, or co-borns' children",
      6: "rivalry, conflict, or estrangement with siblings",
      7: "partnerships or open rivalries formed alongside siblings and peers",
      8: "sudden setbacks to courage, or crises affecting siblings",
      9: "the fortune and guidance siblings or short journeys bring",
      10: "effort and initiative applied toward career and public achievement",
      11: "the gains and support that come through siblings and allies",
      12: "courage spent in isolation, or the quiet loss of sibling closeness",
    },
  },
  D4: {
    domain: "home, property, vehicles, and fixed assets",
    houses: {
      1: "your basic comfort, security, and rootedness",
      2: "the accumulated value of property and fixed family assets",
      3: "effort put into building or improving property",
      4: "the home itself — its stability, comfort, and the mother's domain",
      5: "the enjoyment and creativity expressed through home and possessions",
      6: "property disputes, debts on assets, or discomfort at home",
      7: "shared or jointly owned property, including property gained through marriage",
      8: "sudden change in property status, inheritance, or hidden assets",
      9: "property or fortune connected to a father or higher blessings",
      10: "standing and achievement expressed through visible property and vehicles",
      11: "gains in property, vehicles, and material comfort",
      12: "loss of property, or comfort found instead in retreat and detachment",
    },
  },
  D7: {
    domain: "children, fertility, and legacy carried forward",
    houses: {
      1: "your own vitality and capacity to create and nurture",
      2: "the family line and resources passed down through children",
      3: "the courage and effort invested in raising children",
      4: "the emotional home children create, and comfort found in parenthood",
      5: "children themselves, and progeny most directly",
      6: "obstacles to conception, or friction in the parent-child bond",
      7: "partnership specifically through shared parenthood",
      8: "transformation through childbirth, or challenges to fertility and legacy",
      9: "the fortune and blessings carried forward through one's children",
      10: "legacy expressed through children's standing and achievement",
      11: "gains and fulfillment found through children and their success",
      12: "sacrifice made for children, or distance from one's legacy",
    },
  },
  D9: {
    domain: "marriage, spouse, and the inner strength a planet actually carries",
    houses: {
      1: "your true inner nature and dharmic direction, the self beneath the surface",
      2: "the wealth and family values brought into the marriage",
      3: "the courage and effort invested in sustaining the marital bond",
      4: "the emotional and domestic foundation of married life",
      5: "the intelligence and children born of the marriage",
      6: "friction, obstacles, or strains within the marriage",
      7: "the marriage and spouse themselves, most directly",
      8: "transformation, crisis, or deep intimacy within the marital bond",
      9: "the fortune, dharma, and higher purpose the spouse brings",
      10: "the spouse's or marriage's standing and role in your public life",
      11: "the gains and fulfillment the marriage brings",
      12: "sacrifice, distance, or spiritual release found through the marital bond",
    },
  },
  D10: {
    domain: "career, public standing, and professional achievement",
    houses: {
      1: "your professional identity and how you present yourself at work",
      2: "the income and financial value your career generates",
      3: "the effort, initiative, and skill you apply in your profession",
      4: "the comfort, stability, and support your career provides at home",
      5: "the creativity, strategy, and intelligence you bring to your work",
      6: "obstacles, competition, and the daily grind within your profession",
      7: "professional partnerships, clients, and public-facing dealings",
      8: "sudden career upheaval, transformation, or work done behind the scenes",
      9: "the fortune, mentors, and higher purpose guiding your career",
      10: "the peak visible expression of your career — title, promotions, public recognition",
      11: "professional gains, networks, and the fulfillment of career ambitions",
      12: "career sacrifices, work done away from the spotlight, or a career's ending",
    },
  },
  D12: {
    domain: "parents and ancestry",
    houses: {
      1: "your own inherited nature and family resemblance",
      2: "the wealth and values inherited from your family line",
      3: "the courage or effort your parents modeled for you",
      4: "the mother and the ancestral home, most directly",
      5: "the blessings and creativity passed down from your ancestry",
      6: "strain or distance in the relationship with parents",
      7: "the parents' influence on your partnerships and outlook on relationships",
      8: "transformation or loss connected to parents and lineage",
      9: "the father and the fortune carried through ancestry, most directly",
      10: "a parent's standing and its influence on your own public role",
      11: "gains and support received through parents and ancestry",
      12: "a parent's sacrifices, or a karmic distance from the family line",
    },
  },
  D16: {
    domain: "vehicles, comforts, and general happiness",
    houses: {
      1: "your baseline capacity for contentment and ease",
      2: "the material comforts and possessions the family holds",
      3: "effort spent pursuing comfort, leisure, or travel",
      4: "the vehicles, home comforts, and domestic ease you enjoy",
      5: "pleasure, creativity, and enjoyment found through comfort",
      6: "discomfort, mechanical trouble, or obstacles to ease and travel",
      7: "shared comforts and pleasures enjoyed with a partner",
      8: "sudden disruption to comfort, or hidden sources of happiness",
      9: "the fortune and blessings that bring lasting contentment",
      10: "comfort and happiness expressed and recognized publicly",
      11: "gains in comfort, vehicles, and general happiness",
      12: "the loss of comforts, or contentment found instead in simplicity",
    },
  },
  D20: {
    domain: "spiritual practice and progress on a religious or devotional path",
    houses: {
      1: "your innate spiritual temperament and capacity for devotion",
      2: "the values and resources devoted to spiritual practice",
      3: "the effort and discipline applied to a spiritual path",
      4: "the inner peace and devotional comfort found at home or in the heart",
      5: "devotional creativity, ritual, and inherited spiritual merit",
      6: "obstacles, doubt, or discipline tested on the spiritual path",
      7: "spiritual partnership, gurus, or a shared devotional path",
      8: "deep transformation, mysticism, or occult spiritual practice",
      9: "the guru, higher teaching, and dharma guiding your practice",
      10: "the public or institutional expression of spiritual devotion",
      11: "the fulfillment and community gained through spiritual practice",
      12: "liberation and renunciation — the ultimate release the path offers",
    },
  },
  D24: {
    domain: "education, learning, and accumulated knowledge",
    houses: {
      1: "your natural aptitude for learning",
      2: "the value placed on knowledge within the family",
      3: "effort and initiative applied to study",
      4: "the comfort and support available for education at home",
      5: "intelligence, creativity, and the ability to grasp new subjects",
      6: "obstacles, setbacks, or competition in one's education",
      7: "learning gained through teachers, mentors, or collaborative study",
      8: "deep, specialized, or hidden knowledge and research",
      9: "higher education, philosophy, and the wisdom of teachers",
      10: "recognition and achievement earned through education",
      11: "the gains and opportunities that come from accumulated knowledge",
      12: "knowledge pursued for its own sake, detached from worldly reward",
    },
  },
  D27: {
    domain: "innate strengths and weaknesses, read nakshatra by nakshatra",
    houses: {
      1: "your fundamental innate strength or vulnerability",
      2: "inherited resilience or fragility around resources and speech",
      3: "raw inner courage, or its absence",
      4: "emotional resilience, or the lack of it, rooted in early life",
      5: "innate creative and intellectual gifts, or their weak points",
      6: "vulnerability to obstacles, illness, or self-sabotage",
      7: "innate strength or weakness in how you relate to others",
      8: "resilience or fragility in the face of crisis and transformation",
      9: "an innate sense of fortune and faith, or its absence",
      10: "an innate capacity, or lack of it, to act effectively in the world",
      11: "an innate ability, or difficulty, in realizing gains and goals",
      12: "innate spiritual resilience, or vulnerability to loss and isolation",
    },
  },
  D30: {
    domain: "misfortunes, difficulties, and the finer texture of a marriage beyond the Navamsa",
    houses: {
      1: "vulnerabilities in your basic constitution and life path",
      2: "financial misfortune or strain within the family",
      3: "setbacks tied to courage, siblings, or short undertakings",
      4: "domestic difficulty, or strain in the bond with the mother",
      5: "misfortune touching children or creative pursuits",
      6: "the specific illnesses, debts, or enmities most likely to trouble you",
      7: "the finer, harder texture of the marriage beyond the Navamsa's broad promise",
      8: "the specific nature of crises, loss, or transformation you may face",
      9: "obstacles to fortune, faith, or a father's support",
      10: "professional setbacks or reputational difficulty",
      11: "frustration or delay in realizing gains",
      12: "the deepest losses, isolation, or hidden self-undoing",
    },
  },
  D40: {
    domain: "auspicious and inauspicious effects inherited from the maternal line",
    houses: {
      1: "temperament inherited through the maternal line",
      2: "family wealth and values carried through the mother's side",
      3: "courage or effort patterns inherited maternally",
      4: "the maternal home and a mother's direct blessings or burdens",
      5: "creative or intellectual gifts inherited maternally",
      6: "obstacles or friction inherited through the maternal line",
      7: "relationship patterns inherited or influenced maternally",
      8: "transformation or crisis connected to the maternal lineage",
      9: "fortune and dharma carried through the maternal line",
      10: "standing or achievement influenced by maternal blessings",
      11: "gains and support drawn from the maternal side",
      12: "losses or karmic burdens carried through the maternal line",
    },
  },
  D45: {
    domain: "general character and conduct, inherited from the paternal line",
    houses: {
      1: "your basic character and conduct, as shaped by the paternal line",
      2: "values and resources inherited through the father's side",
      3: "courage and conduct modeled by paternal example",
      4: "emotional grounding, or its absence, from the paternal line",
      5: "intelligence and conduct expressed through paternal inheritance",
      6: "conduct tested under obstacles or paternal-line friction",
      7: "conduct and character as expressed in partnership",
      8: "character revealed under transformation or crisis",
      9: "conduct shaped by a father and paternal dharma directly",
      10: "character and conduct as expressed in public and professional life",
      11: "conduct rewarded through gains and social standing",
      12: "conduct in solitude, sacrifice, or the paternal line's quiet burdens",
    },
  },
  D60: {
    domain: "the finest-grained classical division — past-life karma and overall life texture",
    houses: {
      1: "the karmic imprint carried into this life's very identity",
      2: "karmic patterns around wealth and family carried from past lives",
      3: "karmic courage or fear carried into this life's efforts",
      4: "karmic emotional patterns rooted in the past, shaping home life",
      5: "past-life merit expressed as intelligence, creativity, or fortune with children",
      6: "karmic debts, obstacles, or old enmities resurfacing",
      7: "karmic patterns replaying through partnership and marriage",
      8: "the deepest past-life karma, transformation, and hidden inheritance",
      9: "past-life merit expressed as fortune, faith, and dharma",
      10: "karma expressed through this life's career and public role",
      11: "karmic gains, or the fruits of past merit, realized as achievement",
      12: "the karmic release, loss, or liberation this life is meant to complete",
    },
  },
};
