export interface GlossaryTerm {
  term: string;
  definition: string;
}

export const GLOSSARY: GlossaryTerm[] = [
  { term: "Antardasha", definition: "The sub-period of a Vimshottari Mahadasha, ruled by one of the nine dasha lords in turn — the second of the three levels this site computes." },
  { term: "Ashtakavarga", definition: "A points-based (bindu) system that scores each sign's relative support from the seven classical planets and the Ascendant, used mainly for weighing transit strength." },
  { term: "Ayanamsa", definition: "The angular offset between the tropical zodiac (fixed to the equinox) and the sidereal zodiac (fixed to the star field) — the correction that turns a Western tropical position into a Vedic sidereal one." },
  { term: "Bhava", definition: "House. One of the twelve divisions of the chart counted from the Ascendant, each governing a different area of life." },
  { term: "Bhukti", definition: "Another name for Antardasha — the sub-period within a Mahadasha." },
  { term: "Chesta Bala", definition: "One of the six components of Shadbala — a planet's motional strength, generally highest when retrograde or moving unusually slowly." },
  { term: "Dasha", definition: "A planetary period system used to time when a planet's significations become active in a person's life. Vimshottari Dasha, based on the Moon's nakshatra, is the most widely used." },
  { term: "Debilitation (Neecha)", definition: "The sign in which a planet is considered weakest, classically the sign directly opposite its exaltation sign." },
  { term: "Dig Bala", definition: "Directional strength — one of the six Shadbala components, based on how close a planet sits to the house where it is classically strongest." },
  { term: "Dignity", definition: "The overall quality of a planet's placement by sign — exalted, in its own sign, in a friend's or enemy's sign, debilitated, and so on." },
  { term: "Drishti", definition: "Aspect — the influence one planet casts onto another house or planet. All planets aspect the 7th house from themselves; Mars, Jupiter, and Saturn cast additional special aspects." },
  { term: "Dushthana", definition: "The three difficult houses — 6th, 8th, and 12th — associated with obstacles, transformation, and loss respectively." },
  { term: "Graha", definition: "Planet, in the classical sense — the nine grahas used in Vedic astrology are the Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu." },
  { term: "Kaala Bala", definition: "Temporal strength — one of the six Shadbala components, reflecting a planet's strength based on time of day, lunar phase, and other time-based factors." },
  { term: "Karaka", definition: "A planet's natural significator role — the graha classically associated with a particular house, relationship, or life theme regardless of where it sits in a specific chart." },
  { term: "Kendra", definition: "The four angular houses — 1st, 4th, 7th, and 10th — considered the strongest and most structurally important houses in the chart." },
  { term: "Kuja Dosha (Mangal Dosha)", definition: "A classical affliction where Mars sits in one of several specific houses from the Ascendant, traditionally weighed carefully in marriage compatibility." },
  { term: "Lagna", definition: "The Ascendant — the sign rising on the eastern horizon at the exact moment and place of birth, and the reference point every house in the chart is counted from." },
  { term: "Mahadasha", definition: "The major (first-level) period in the Vimshottari Dasha system, lasting anywhere from 6 to 20 years depending on the ruling planet." },
  { term: "Maraka", definition: "Literally \"killer\" — the 2nd and 7th houses and their lords, classically implicated in dasha periods associated with health crises or endings, not literal death in every case." },
  { term: "Moolatrikona", definition: "A degree range within (or adjacent to) a planet's own sign where it is considered even stronger than in an ordinary own-sign placement." },
  { term: "Nadi", definition: "One of three groupings of the 27 nakshatras (Aadi, Madhya, Antya) used in certain compatibility and remedial systems; also the name of a separate predictive tradition (Nadi astrology) not used on this site." },
  { term: "Naisargika Bala", definition: "Natural strength — one of the six Shadbala components, a fixed ranking of the classical planets by inherent brightness/strength (Sun highest, Saturn lowest)." },
  { term: "Nakshatra", definition: "One of the 27 lunar mansions the zodiac is divided into (13°20' each), each with a ruling planet, deity, and symbolic character. The Moon's nakshatra at birth sets the starting point of Vimshottari Dasha." },
  { term: "Navamsa", definition: "The D9 divisional chart — the most consulted varga after the main Rasi chart, read for marriage and for the underlying strength of any planet." },
  { term: "Pada", definition: "One of the four 3°20' quarters of a nakshatra; also a technical term (Arudha Pada) in a separate, more advanced predictive technique not covered here." },
  { term: "Panchadha Maitri", definition: "The five-fold combined friendship between two planets, blending their fixed natural relationship with their temporary (house-distance-based) relationship in a specific chart." },
  { term: "Paksha", definition: "The lunar fortnight — waxing (Shukla Paksha) or waning (Krishna Paksha) — measured from the angular distance between the Moon and Sun." },
  { term: "Parivartana", definition: "A mutual exchange, where two planets each sit in a sign ruled by the other — classically read as strongly connecting the two houses and significations involved." },
  { term: "Pratyantardasha", definition: "The third-level sub-period within an Antardasha — the finest level of Vimshottari timing this site computes." },
  { term: "Rahu / Ketu", definition: "The lunar nodes — the points where the Moon's orbit crosses the ecliptic. Not physical bodies, but treated as full grahas in Vedic astrology, always exactly 180° apart." },
  { term: "Rashi", definition: "Zodiac sign — one of the twelve 30° divisions of the sidereal zodiac, from Aries (Mesha) through Pisces (Meena)." },
  { term: "Retrograde (Vakri)", definition: "The apparent backward motion of a planet as seen from Earth — classically read as intensifying or internalizing that planet's significations." },
  { term: "Sade Sati", definition: "The roughly seven-and-a-half-year period when transiting Saturn moves through the sign before, the sign of, and the sign after a person's natal Moon sign." },
  { term: "Shadbala", definition: "\"Six-fold strength\" — a composite classical measure of a planet's overall strength, combining positional, directional, temporal, motional, natural, and aspectual components." },
  { term: "Sidereal Zodiac", definition: "The zodiac used in Vedic astrology, fixed to the actual positions of the constellations rather than to the equinox — offset from the tropical zodiac by the ayanamsa." },
  { term: "Sthana Bala", definition: "Positional strength — the largest of the six Shadbala components, built from a planet's dignity across several divisional charts plus its house placement." },
  { term: "Trikona", definition: "The three \"trine\" houses — 1st, 5th, and 9th — classically considered the most fortunate and auspicious houses in the chart." },
  { term: "Upachaya", definition: "The \"growing\" houses — 3rd, 6th, 10th, and 11th — classically read as improving over time rather than delivering their full results immediately." },
  { term: "Varga", definition: "A divisional chart — any of the sixteen classical subdivisions of the Rasi chart (D2 through D60), each used to examine a specific area of life in finer detail." },
  { term: "Vimshottari Dasha", definition: "The most widely used dasha system in Vedic astrology, dividing a 120-year cycle among the nine grahas in a fixed order, starting point set by the Moon's natal nakshatra." },
  { term: "Yoga", definition: "A specific classical planetary combination believed to produce a particular result — ranging from the auspicious (Raja Yogas, Dhana Yogas) to the challenging (Kemadruma, Shakat)." },
];
