export interface ReferenceYoga {
  name: string;
  category: "Raja Yoga" | "Dhana Yoga" | "Mahapurusha Yoga" | "Chandra Yoga" | "Dosha" | "Other";
  definition: string;
  effect: string;
  /** Whether this site's calculation engine (src/lib/astrology/yogas.ts / kundali.ts) actually detects this on a real chart, or whether it's reference-only. */
  detectedByEngine: boolean;
}

/**
 * A broader classical yoga/dosha glossary than the engine computes. The
 * `detectedByEngine: true` entries mirror the exact rule coded in
 * `../yogas.ts` (the 16 Mahapurusha/Chandra/Raja combinations) and
 * `../kundali.ts`'s `detectDoshas` (the 3 doshas) — definitions here match
 * what the engine specifically checks, not just the general classical form.
 * The `detectedByEngine: true` entries are reference-only: well-known
 * classical combinations this site doesn't (yet) compute on a live chart.
 */
export const YOGA_REFERENCE: ReferenceYoga[] = [
  {
    name: "Ruchaka Yoga",
    category: "Mahapurusha Yoga",
    definition: "Mars sits in a kendra (1st, 4th, 7th, or 10th house from the Lagna) in its own sign or exalted.",
    effect: "Physical courage, leadership, competitive drive, and a commanding presence.",
    detectedByEngine: true,
  },
  {
    name: "Bhadra Yoga",
    category: "Mahapurusha Yoga",
    definition: "Mercury sits in a kendra in its own sign or exalted.",
    effect: "Sharp intellect, business acumen, and articulate, persuasive communication.",
    detectedByEngine: true,
  },
  {
    name: "Hamsa Yoga",
    category: "Mahapurusha Yoga",
    definition: "Jupiter sits in a kendra in its own sign or exalted.",
    effect: "Wisdom, ethical conduct, and a respected, teacher-like standing.",
    detectedByEngine: true,
  },
  {
    name: "Malavya Yoga",
    category: "Mahapurusha Yoga",
    definition: "Venus sits in a kendra in its own sign or exalted.",
    effect: "Beauty, artistic talent, luxury, and comfortable material circumstances.",
    detectedByEngine: true,
  },
  {
    name: "Sasha Yoga",
    category: "Mahapurusha Yoga",
    definition: "Saturn sits in a kendra in its own sign or exalted.",
    effect: "Authority and leadership earned through discipline, patience, and endurance.",
    detectedByEngine: true,
  },
  {
    name: "Gaj Kesari Yoga",
    category: "Chandra Yoga",
    definition: "Jupiter sits in a kendra (1st, 4th, 7th, or 10th) counted from the Moon.",
    effect: "Wisdom, a strong reputation, and steady, resilient prosperity.",
    detectedByEngine: true,
  },
  {
    name: "Chandra-Mangal Yoga",
    category: "Chandra Yoga",
    definition: "The Moon and Mars are conjunct (share a sign).",
    effect: "Drive, resourcefulness, and an active ability to generate wealth.",
    detectedByEngine: true,
  },
  {
    name: "Kemadruma Yoga",
    category: "Chandra Yoga",
    definition: "No planet besides the Sun occupies the sign before, after or with the Moon, and neither the Moon nor any planet stands in a kendra from it (any of these cancels the yoga).",
    effect: "Classically a caution for isolation or struggle — read against the strength of the rest of the chart, not in isolation.",
    detectedByEngine: true,
  },
  {
    name: "Neechabhanga Raja Yoga",
    category: "Raja Yoga",
    definition: "A debilitated planet's dispositor (the lord of its debilitation sign) sits in a kendra from the Lagna or the Moon, cancelling the debilitation.",
    effect: "Turns an apparent weakness into a source of unexpected rise or achievement.",
    detectedByEngine: true,
  },
  {
    name: "Vipareeta Raja Yoga",
    category: "Raja Yoga",
    definition: "The lord of one dushthana (6th, 8th, or 12th house) is placed in a different dushthana.",
    effect: "Strength or success that emerges specifically from overcoming difficulty rather than from easy circumstance.",
    detectedByEngine: true,
  },
  {
    name: "Parivartana Yoga",
    category: "Raja Yoga",
    definition: "Two planets mutually exchange signs — each sits in a sign the other rules.",
    effect: "Strongly links the two houses and significations involved, for better or worse depending on which houses.",
    detectedByEngine: true,
  },
  {
    name: "Adhi Yoga",
    category: "Chandra Yoga",
    definition: "Only benefic planets (Mercury, Jupiter, and/or Venus) occupy the 6th, 7th, or 8th house from the Moon, with no malefic among them.",
    effect: "Sustained authority and a real ability to overcome opposition.",
    detectedByEngine: true,
  },
  {
    name: "Shakat Yoga",
    category: "Chandra Yoga",
    definition: "The Moon sits in the 6th, 8th, or 12th house from Jupiter.",
    effect: "A classical caution for fluctuating fortune, needing Jupiter's other strengths to offset it.",
    detectedByEngine: true,
  },
  {
    name: "Guru Chandal Yoga",
    category: "Other",
    definition: "Jupiter is conjunct Rahu.",
    effect: "Jupiter's wisdom filtered through Rahu's unconventional, amplifying influence — for better or worse depending on the rest of the chart.",
    detectedByEngine: true,
  },
  {
    name: "Budh-Aditya Yoga",
    category: "Other",
    definition: "The Sun and Mercury are conjunct.",
    effect: "Sharp intellect and articulate, confident communication.",
    detectedByEngine: true,
  },
  {
    name: "Amala Yoga",
    category: "Raja Yoga",
    definition: "Only a benefic (Mercury, Jupiter, and/or Venus), with no malefic, occupies the 10th house from the Moon or from the Lagna.",
    effect: "A lasting, largely unblemished good reputation.",
    detectedByEngine: true,
  },
  {
    name: "Mangal Dosha (Kuja Dosha)",
    category: "Dosha",
    definition: "Mars occupies the 1st, 2nd, 4th, 7th, 8th, or 12th house from the Lagna.",
    effect: "Classically weighed carefully in marriage compatibility; traditionally read as bringing friction or intensity into partnership unless matched or mitigated.",
    detectedByEngine: true,
  },
  {
    name: "Kaal Sarp Dosha",
    category: "Dosha",
    definition: "All seven classical planets fall on one side of the Rahu-Ketu axis.",
    effect: "A karmic, all-or-nothing quality to the chart's themes — often read as obstruction and delay followed by breakthrough once the underlying pattern is worked through.",
    detectedByEngine: true,
  },
  {
    name: "Pitra Dosha",
    category: "Dosha",
    definition: "Rahu or Ketu occupies the 9th house, or the Sun is conjunct a lunar node.",
    effect: "Classically linked to unresolved afflictions relating to ancestry and the paternal line.",
    detectedByEngine: true,
  },
  {
    name: "Dhana Yoga",
    category: "Dhana Yoga",
    definition: "A lord of the 2nd or 11th house (the wealth houses) is conjunct, in mutual 7th aspect with, or exchanges signs with the lord of the Lagna, 2nd, 5th, 9th or 11th.",
    effect: "Financial gain and the steady accumulation of resources.",
    detectedByEngine: true,
  },
  {
    name: "Kendra-Trikona Raja Yoga",
    category: "Raja Yoga",
    definition: "A lord of one of the four kendras (1st/4th/7th/10th) connects — by conjunction, mutual aspect, or sign exchange — with a lord of one of the three trikonas (1st/5th/9th).",
    effect: "Power, status, and authority — the broad classical category that most specifically named Raja Yogas (including several above) are considered special cases of.",
    detectedByEngine: true,
  },
  {
    name: "Saraswati Yoga",
    category: "Other",
    definition: "Jupiter, Venus, and Mercury are together placed in a kendra, a trikona, or the 2nd house, with Jupiter itself in a strong condition.",
    effect: "Deep learning, eloquence, and accomplishment in scholarship or the arts.",
    detectedByEngine: true,
  },
  {
    name: "Lakshmi Yoga",
    category: "Raja Yoga",
    definition: "The 9th lord is in a kendra or trikona in its own or exalted sign, and the Lagna lord is strong (own, exalted or friend sign).",
    effect: "Wealth, grace, and good fortune that tends to arrive without excessive struggle.",
    detectedByEngine: true,
  },
  {
    name: "Shubha Kartari Yoga",
    category: "Other",
    definition: "The 2nd and 12th houses from the Lagna hold only benefics (Mercury, Jupiter, Venus), hemming the Lagna between them.",
    effect: "A protective, supportive quality around whatever the flanked house or planet signifies.",
    detectedByEngine: true,
  },
  {
    name: "Papa Kartari Yoga",
    category: "Other",
    definition: "The 2nd and 12th houses from the Lagna hold only malefics, hemming the Lagna between them.",
    effect: "Pressure, constriction, and obstacles around whatever the flanked house or planet signifies.",
    detectedByEngine: true,
  },
  {
    name: "Sunapha Yoga",
    category: "Chandra Yoga",
    definition: "A planet other than the Sun occupies the 2nd house counted from the Moon.",
    effect: "Self-made wealth, skill, and a solid personal reputation.",
    detectedByEngine: true,
  },
  {
    name: "Anapha Yoga",
    category: "Chandra Yoga",
    definition: "A planet other than the Sun occupies the 12th house counted from the Moon.",
    effect: "Personal comfort, good health, and refined tastes.",
    detectedByEngine: true,
  },
  {
    name: "Durudhara Yoga",
    category: "Chandra Yoga",
    definition: "Planets other than the Sun occupy both the 2nd and 12th houses counted from the Moon at once.",
    effect: "Combines Sunapha's and Anapha's benefits — wealth and comfort together.",
    detectedByEngine: true,
  },
  {
    name: "Vasumati Yoga",
    category: "Dhana Yoga",
    definition: "Benefic planets occupy the Upachaya houses (3rd, 6th, 10th, or 11th) counted from the Lagna or from the Moon.",
    effect: "Wealth and resources that build steadily and increase over a lifetime.",
    detectedByEngine: true,
  },
  {
    name: "Grahan Yoga (Grahana Yoga)",
    category: "Other",
    definition: "The Sun or Moon shares a sign with Rahu or Ketu — an \"eclipse\" combination.",
    effect: "Classically read as obscuring or complicating that luminary's significations until it's consciously worked with.",
    detectedByEngine: true,
  },
  {
    name: "Vish Yoga",
    category: "Other",
    definition: "The Moon is conjunct Saturn, or the two aspect each other (also called Punarphoo).",
    effect: "Emotional heaviness, delay, or restriction — but also real depth and resilience once matured.",
    detectedByEngine: true,
  },
  {
    name: "Angarak Yoga",
    category: "Other",
    definition: "Mars shares a sign with Rahu.",
    effect: "Amplified aggression or impulsiveness — channelled productively when the rest of the chart provides support and outlet.",
    detectedByEngine: true,
  },
  {
    name: "Yogakaraka Planet",
    category: "Raja Yoga",
    definition: "A planet that rules both a kendra (4th/7th/10th) and a trikona (5th/9th) for the Lagna.",
    effect: "The single most beneficial planet of the chart; its dasha tends to deliver status and success, if it is not in a dusthana or debilitated.",
    detectedByEngine: true,
  },
  {
    name: "Dharma-Karmadhipati Yoga",
    category: "Raja Yoga",
    definition: "The 9th and 10th lords are conjunct, in mutual aspect or exchange signs.",
    effect: "Joins fortune and dharma to career — recognition for one's work.",
    detectedByEngine: true,
  },
  {
    name: "Harsha Yoga",
    category: "Raja Yoga",
    definition: "The 6th lord sits in the 6th, 8th or 12th house (a Vipareeta Raja Yoga).",
    effect: "Victory over rivals, good health and contentment.",
    detectedByEngine: true,
  },
  {
    name: "Sarala Yoga",
    category: "Raja Yoga",
    definition: "The 8th lord sits in the 6th, 8th or 12th house (a Vipareeta Raja Yoga).",
    effect: "Longevity, courage and fame from overcoming hardship.",
    detectedByEngine: true,
  },
  {
    name: "Vimala Yoga",
    category: "Raja Yoga",
    definition: "The 12th lord sits in the 6th, 8th or 12th house (a Vipareeta Raja Yoga).",
    effect: "Thrift, integrity and a spotless reputation.",
    detectedByEngine: true,
  },
  {
    name: "Kahala Yoga",
    category: "Raja Yoga",
    definition: "The 4th and 9th lords are in kendras from each other and the Lagna lord is strong or in a kendra.",
    effect: "Boldness, command and landed prosperity.",
    detectedByEngine: true,
  },
  {
    name: "Chamara Yoga",
    category: "Raja Yoga",
    definition: "The Lagna lord is exalted in a kendra and Jupiter joins or aspects it.",
    effect: "Learning, honour and wide recognition.",
    detectedByEngine: true,
  },
  {
    name: "Shankha Yoga",
    category: "Raja Yoga",
    definition: "The 5th and 6th lords are in kendras from each other and the Lagna lord is strong.",
    effect: "Longevity, fortune and a principled life.",
    detectedByEngine: true,
  },
  {
    name: "Bheri Yoga",
    category: "Raja Yoga",
    definition: "Venus, Jupiter and the Lagna lord are all in kendras, with the 9th lord strong.",
    effect: "Wealth, family happiness and long life.",
    detectedByEngine: true,
  },
  {
    name: "Parvata Yoga",
    category: "Raja Yoga",
    definition: "The Lagna lord is in a kendra, a benefic is in a kendra, and the 6th and 8th houses hold no malefic.",
    effect: "A mountain-like standing in learning and public life.",
    detectedByEngine: true,
  },
  {
    name: "Daridra Yoga",
    category: "Dhana Yoga",
    definition: "Both the 2nd and 11th lords sit in the 6th, 8th or 12th houses.",
    effect: "Uneven savings and gains that need careful management.",
    detectedByEngine: true,
  },
  {
    name: "Shrapit Dosha",
    category: "Dosha",
    definition: "Saturn shares a sign with Rahu.",
    effect: "A karmic delay, traditionally eased by steady service and Shani remedies.",
    detectedByEngine: true,
  },
  {
    name: "Guru-Mangala Yoga",
    category: "Other",
    definition: "Jupiter shares a sign with Mars.",
    effect: "Wisdom joined to drive — enterprise, law and teaching.",
    detectedByEngine: true,
  },
  {
    name: "Pravrajya Yoga",
    category: "Other",
    definition: "Four or more of the seven planets (Sun to Saturn) share a single sign.",
    effect: "A pull towards renunciation, study or a life apart from the crowd.",
    detectedByEngine: true,
  },
  {
    name: "Sankhya Yogas (Veena, Dama, Pasha, Kedara, Shoola, Yuga, Gola)",
    category: "Other",
    definition: "The seven planets (Sun to Saturn) occupy 7, 6, 5, 4, 3, 2 or 1 signs respectively.",
    effect: "Temperament by spread: refined (Veena), generous (Dama), industrious (Pasha), land-bound (Kedara), forceful (Shoola), wealth made and spent (Yuga), concentrated (Gola).",
    detectedByEngine: true,
  },
  {
    name: "Ashraya Yogas (Rajju, Musala, Nala)",
    category: "Other",
    definition: "All seven planets are in movable (Rajju), fixed (Musala) or dual (Nala) signs.",
    effect: "Restless and ambitious (Rajju), steady and resolute (Musala), adaptable and many-sided (Nala).",
    detectedByEngine: true,
  },
  {
    name: "Dala Yogas (Mala, Sarpa)",
    category: "Other",
    definition: "Mercury, Jupiter and Venus fill three different kendras (Mala); or the Sun, Mars and Saturn do (Sarpa).",
    effect: "Comfort and a pleasing life (Mala); a sharp, guarded path (Sarpa).",
    detectedByEngine: true,
  },
  {
    name: "Akriti Yogas (Kamala, Vajra, Yava, Gada, Vapi, Yupa, Shara, Shakti, Danda, Nauka, Koota, Chhatra, Chapa)",
    category: "Other",
    definition: "The seven planets form a pattern of houses from the Lagna: all four kendras (Kamala), benefics in 1/7 and malefics in 4/10 (Vajra) or the reverse (Yava), two adjacent kendras (Gada), all in panaphara or apoklima houses (Vapi), four consecutive houses from a kendra (Yupa, Shara, Shakti, Danda), or seven consecutive houses from a kendra (Nauka, Koota, Chhatra, Chapa).",
    effect: "Each Nabhasa pattern carries its own temperament, from fame and virtue (Kamala) to enterprise (Chapa).",
    detectedByEngine: true,
  },
];
